APP:
  Name: cattle
  Service: cattle
  LogPath: /tmp
  LogLevel: DEBUG
  Development: true
Server:
  RunMode: debug
  HTTPPort: 2025
  ReadTimeout: 180
  WriteTimeout: 60
JWT:
  JwtSecret: cattle
  JwtExpire: 828000
  JwtIssuer: cattle
MySQL:
  Host: 59.110.11.17
  Username: test_user
  Password: Test_123
  Port: 7829
  DBName: cattle
  MaxIdleConns: 10 #空闲连接池中连接的最大数量
  MaxOpenConns: 100 #打开数据库连接的最大数量
  ConnMaxLifetime: 1 #连接可复用的最大时间（小时）
Cron:
  Status: 0 # 是否启动定时任务
